name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Retrieve Git username
        id: git_username
        run: echo "::set-output name=username::$(git log -1 --pretty=format:%an)"

      - name: Retrieve Git email
        id: git_email
        run: echo "::set-output name=email::$(git log -1 --pretty=format:%ae)"

      - name: Set Git Credentials
        run: |
          git config --global user.name "${{ steps.git_username.outputs.username }}"
          git config --global user.email "${{ steps.git_email.outputs.email }}"

      - name: Build
        run: npm run build

      - name: Deploy to Github Pages
        run: npm run deploy
